# Generated by Django 4.2.27 on 2026-02-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(help_text='Email', max_length=254, unique=True),
        ),
    ]
